public class HealthHistory
{
    public int Id { get; set; }
    public string Titulo { get; set; }
    public string Nombre { get; set; }
    public string Tipo_consulta { get; set; }
	public string Nro_documento { get; set; }
	public DateTime Fecha_ingreso { get; set; }
	public string Obra_social { get; set; }
    public string Afiliado_nro { get; set; }	
    public string Edad { get; set; }
	public DateTime Fecha_de_nacimiento { get; set; }
	public string Estado_civil { get; set; }
	public string Ocupacion_actual { get; set; }
	public string Ocupaciones_previas { get; set; }
	public string Domicilio { get; set; }
	public string Telefono { get; set; }
	public string Familiar_responsable_legal { get; set; }
	public string Parentesco { get; set; }
	public string Domicilio_parentesco { get; set; }
	public string Telefono_parentesco { get; set; }
	public string Motivo_de_consulta { get; set; }
	public string Enfermedad_actual { get; set; }
	public string Enfermedades_concurrentes { get; set; }
	public string Antecedentes_clinicos_y_quirurgicos { get; set; }
	public string Tratamientos_psiquiatricospsicologicos_previos { get; set; }
	public string Esta_tomando_alguna_medicacion { get; set; }
	public string Aspecto_psiquico { get; set; }
	public string Actitud_psiquica { get; set; }
	public string Actividad { get; set; }
	public string Orientacion { get; set; }
	public string Conciencia { get; set; }
	public string Memoria { get; set; }
	public string Atencion { get; set; }
	public string Ideacion { get; set; }
	public string Curso_del_pensamiento { get; set; }
	public string Contenido_del_pensamiento { get; set; }
	public string Sensopersepcion { get; set; }
	public string Afectividad { get; set; }
	public string Inteligencia { get; set; }
	public string Juicio { get; set; }
	public string Control_esfinteres { get; set; }
	public string Lenguaje { get; set; }
	public string Sueno { get; set; }
	public string Diagnostico_cie10_dsm_iv { get; set; }
	public string Antecedentes_personales_personalidad_previa_escolaridad { get; set; }
	public string Grupo_familiar_actual_antecedentes_familiares_vivienda { get; set; }
	public string Evolucion { get; set; }
}